"""IEP6 agent HTTP API. Exposed at /api/agent/* (routed to this service by the
ingress; the SPA proxies /api)."""
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.agent.runtime import answer
from app.core.database import get_session

router = APIRouter(prefix="/api/agent", tags=["agent"])


class QueryIn(BaseModel):
    store_id: str
    question: str


@router.post("/query")
async def query(body: QueryIn, session: AsyncSession = Depends(get_session)) -> dict:
    """Natural-language Q&A grounded in the store's analytics data."""
    return await answer(body.question, body.store_id, session)


@router.get("/insights")
async def insights(store_id: str, limit: int = 5,
                   session: AsyncSession = Depends(get_session)) -> dict:
    """Latest stored insight reports for a store (generated by the scheduler)."""
    rows = (await session.execute(
        text("SELECT kind, title, body, created_at FROM agent_insights "
             "WHERE store_id = :sid ORDER BY created_at DESC LIMIT :lim"),
        {"sid": store_id, "lim": limit})).mappings().all()
    return {"store_id": store_id, "insights": [dict(r) for r in rows]}


@router.get("/alerts")
async def alerts(store_id: str, unresolved_only: bool = True,
                 session: AsyncSession = Depends(get_session)) -> dict:
    """Proactive alerts raised by the agent for a store."""
    sql = ("SELECT kind, severity, message, details, created_at, resolved_at "
           "FROM agent_alerts WHERE store_id = :sid")
    if unresolved_only:
        sql += " AND resolved_at IS NULL"
    sql += " ORDER BY created_at DESC LIMIT 50"
    rows = (await session.execute(text(sql), {"sid": store_id})).mappings().all()
    return {"store_id": store_id, "alerts": [dict(r) for r in rows]}
