apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: retail-edge
resources:
  - ../k8s/namespace.yaml
  - redpanda.yaml
  - ../k8s/iaip1-ingestion.yaml
  - ../k8s/iaip2-detector-workers.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
