apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: retail-edge
resources:
  - namespace.yaml
  - redpanda.yaml
  - iaip1-ingestion.yaml
  - iaip2-detector-workers.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
