"""IEP5 — AI Agent schemas.

Defines the input/output contract for the LLM-powered retail insights agent.

Endpoints:
  POST /agent/query
    Input:  AgentQuery
    Output: AgentResponse

  POST /agent/report
    Input:  ReportRequest
    Output: ReportResponse

  GET  /agent/suggestions/{store_id}
    Output: List[Suggestion]
"""
from datetime import datetime
from typing import List, Optional, Dict
from pydantic import BaseModel


# ── Query ────────────────────────────────────────────────────────────────────

class AgentQuery(BaseModel):
    """Natural-language question about retail analytics."""
    store_id: str
    question: str
    context: Optional[Dict] = None       # optional extra context (date range, zone, etc.)


class AgentResponse(BaseModel):
    """Structured answer from the AI agent."""
    answer: str
    confidence: float                     # 0.0–1.0
    sources: List[str] = []              # references to data used
    charts: List[Dict] = []             # optional chart specs for frontend


# ── Reports ──────────────────────────────────────────────────────────────────

class ReportRequest(BaseModel):
    """Request an auto-generated report."""
    store_id: str
    report_type: str                     # "daily_summary" | "zone_analysis" | "anomaly"
    start: Optional[datetime] = None
    end: Optional[datetime] = None


class ReportResponse(BaseModel):
    report_id: str
    store_id: str
    report_type: str
    markdown: str                        # rendered report content
    generated_at: datetime


# ── Suggestions ──────────────────────────────────────────────────────────────

class Suggestion(BaseModel):
    """Proactive insight generated by the agent."""
    id: str
    store_id: str
    category: str                        # "layout" | "staffing" | "merchandising"
    title: str
    detail: str
    priority: str                        # "low" | "medium" | "high"
    created_at: datetime
