"""IEP5 — AI Agent Service: I/O contract.

All request bodies, query parameters, and response payloads are declared here so
every endpoint has an explicit, typed, documented contract.

Endpoint catalogue
------------------

POST /agent/query
    Input :  AgentQuery
    Output:  AgentResponse                    (200)

POST /agent/report
    Input :  ReportRequest
    Output:  ReportResponse                   (200)

GET  /agent/suggestions/{store_id}
    Output:  List[Suggestion]                 (200)

GET  /health
    Output:  HealthResponse                   (200)
"""
from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


# ── Health ────────────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    service: str = "iep5-agent"
    status: str = "ok"


# ── Shared enums ──────────────────────────────────────────────────────────────

ReportType = Literal["daily_summary", "zone_analysis", "anomaly"]
SuggestionCategory = Literal["layout", "staffing", "merchandising"]
Priority = Literal["low", "medium", "high"]


# ── Query ─────────────────────────────────────────────────────────────────────

class AgentQuery(BaseModel):
    """Natural-language question about retail analytics."""
    store_id: str
    question: str
    context: Optional[Dict[str, Any]] = Field(
        None, description="Optional extra context (date range, zone, etc.)"
    )


class ChartSpec(BaseModel):
    """Chart the frontend should render alongside the answer."""
    type: Literal["line", "bar", "pie", "heatmap"]
    title: str
    data: Dict[str, Any] = Field(default_factory=dict)


class AgentResponse(BaseModel):
    """Structured answer from the AI agent."""
    answer: str
    confidence: float = Field(..., ge=0.0, le=1.0)
    sources: List[str] = Field(default_factory=list, description="References to data used")
    charts: List[ChartSpec] = Field(default_factory=list)


# ── Reports ───────────────────────────────────────────────────────────────────

class ReportRequest(BaseModel):
    """Request an auto-generated report."""
    store_id: str
    report_type: ReportType
    start: Optional[datetime] = None
    end: Optional[datetime] = None


class ReportResponse(BaseModel):
    report_id: str
    store_id: str
    report_type: ReportType
    markdown: str = Field(..., description="Rendered report content")
    generated_at: datetime


# ── Suggestions ───────────────────────────────────────────────────────────────

class Suggestion(BaseModel):
    """Proactive insight generated by the agent."""
    id: str
    store_id: str
    category: SuggestionCategory
    title: str
    detail: str
    priority: Priority
    created_at: datetime
