apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: retail-edge
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - dev-stateful.yaml
  - redpanda.yaml
  - eep.yaml
  - frontend.yaml
  - iaip1-ingestion.yaml
  - iaip2-detector-workers.yaml
  - iep3-reconciliation.yaml
  - keda-scaledobjects.yaml
