# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.edge_agent.app.grpc_generated import iep1_control_pb2 as iep1__control__pb2

GRPC_GENERATED_VERSION = '1.64.3'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in iep1_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class Iep1ControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddCamera = channel.unary_unary(
                '/retailvision.iep1.v1.Iep1Control/AddCamera',
                request_serializer=iep1__control__pb2.CameraConfig.SerializeToString,
                response_deserializer=iep1__control__pb2.AddCameraResponse.FromString,
                _registered_method=True)
        self.RemoveCamera = channel.unary_unary(
                '/retailvision.iep1.v1.Iep1Control/RemoveCamera',
                request_serializer=iep1__control__pb2.RemoveCameraRequest.SerializeToString,
                response_deserializer=iep1__control__pb2.RemoveCameraResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/retailvision.iep1.v1.Iep1Control/GetStatus',
                request_serializer=iep1__control__pb2.Empty.SerializeToString,
                response_deserializer=iep1__control__pb2.Iep1StatusResponse.FromString,
                _registered_method=True)


class Iep1ControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Iep1ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCamera,
                    request_deserializer=iep1__control__pb2.CameraConfig.FromString,
                    response_serializer=iep1__control__pb2.AddCameraResponse.SerializeToString,
            ),
            'RemoveCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveCamera,
                    request_deserializer=iep1__control__pb2.RemoveCameraRequest.FromString,
                    response_serializer=iep1__control__pb2.RemoveCameraResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=iep1__control__pb2.Empty.FromString,
                    response_serializer=iep1__control__pb2.Iep1StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'retailvision.iep1.v1.Iep1Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('retailvision.iep1.v1.Iep1Control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Iep1Control(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retailvision.iep1.v1.Iep1Control/AddCamera',
            iep1__control__pb2.CameraConfig.SerializeToString,
            iep1__control__pb2.AddCameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retailvision.iep1.v1.Iep1Control/RemoveCamera',
            iep1__control__pb2.RemoveCameraRequest.SerializeToString,
            iep1__control__pb2.RemoveCameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retailvision.iep1.v1.Iep1Control/GetStatus',
            iep1__control__pb2.Empty.SerializeToString,
            iep1__control__pb2.Iep1StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
