apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-edge
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: eep
                port:
                  number: 8000
          - path: /internal
            pathType: Prefix
            backend:
              service:
                name: eep
                port:
                  number: 8000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: eep
                port:
                  number: 8000
