apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: retail-edge
resources:
  - namespace.yaml
  - redis.yaml
  - eep.yaml
  - hpa.yaml
  - frontend.yaml
  - ingress.yaml
  - configmap.yaml
  - secrets.yaml
  - ecr-refresh.yaml
